name: learn-tf-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install-makefile:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y make